#端口号配置
server:
  port: 8089

#jwt配置
jwt:
  secret: com.itmk
  #30分钟过期
  expiration: 1800000

#登录请求配置
itmk:
  loginUrl: /api/user/login

#数据库连接配置
spring:
  redis:
    expire: 60000
    database: 0 # Redis使用的库
    host: localhost
    port: 6379 #端口号
    password:   #redis密码
    #    lettuce:
    #      pool:
    #        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8       # 连接池中的最大空闲连接
    #        min-idle: 1       # 连接池中的最小空闲连接
    timeout: 10000        #  连接超时时间（毫秒）
    cache:
      type: redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue-element-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
